# Generated by Django 5.2 on 2025-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='프로필 사진')),
                ('introduction', models.TextField(verbose_name='한 줄 소개')),
                ('birthday', models.DateField(verbose_name='생일')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
            ],
        ),
    ]
